---
- hosts: localhost
  connection: localhost
  become: "yes"
  roles:
    - role: leesoh.metasploit
  tasks:
    - crivetimihai.workstation.baseline:
    - crivetimihai.workstation.pip:
    - crivetimihai.workstation.packages:
    - crivetimihai.workstation.secure:
    - crivetimihai.server.xrdp:
    - git:
        repo: https://github.com/offensive-security/exploitdb.git
        dest: /opt/exploitdb
    - git:
        repo: https://github.com/offensive-security/exploitdb-papers.git
        dest: /opt/exploitdb-papers
    - git:
        repo: https://gitlab.com/kalilinux/packages/webshells
        dest: /opt/kali/webshells
